$seq = "attgggaaaaaacagaacagaaaaactggaaactctaaaacgcagagcgcctctcctcct
ccaaaggaatgtagttcctcaccagcaacggaacaaagctggatggagaatgactttgat
gagctgagagaagaaggcttcagacaatcaaattactctgagctacggaaggacattcaa
accaaaggcaaagaagttgaaaactttgaaaaaaatttagaagaatgtaaaactagaata
accaatacagagaagtgcttaaaggagctgatggagctgaaaaccaaggctcgagaacta
tgtgaagaatgcagaagcctcaggagccgatgcaatcaactggaagaaagggtatcagtg
atggaagatgaaatgaatgaaatgaagcgagaagggaagtttagagaaaaaagaataaaa
agaaatgagcaaagcctccaagaaatatgggactatgtgagaccaaatctacgtccgatt
ggtgtacctgaaagtgacggggagaatggaaccaagttggaaaacactctgcaggatact
atccaggagaacttccccaatctagcaaggcaggccaacgttcagattcaggaaatacag
agaacaccacaaagatactcctcgagaagagcaactccaagacacataattgtcagattc
accaaagttgaaatgaaggaaaaaatgttaagggcagccagagagaaaggtcgggttacc
ctcaaagggaagcccatcagactaacagcggatctctcggcagaaaccctacaagccaga
agagagtgggggccaatattcaacattcttaaagaaaagaattttcaacccagaatttca
tatccagccaaactaagcttcataagtgaaggagaaataaaatactttacagacaagcaa
atgctgagagattttgtcaccaccaggcctgccctaaaagagctcctgaaggaagtgcta
aacatggaaaggaacaaccggtaccagccgctgcaaaatcatgccaaaatg";
$seq =~ s/\n//g;
print length($seq);